/*
 * Created on 06.02.2009, 18:16:56
 */

package bz.asd.autodb.gui;

/**
 *
 * @author lars
 */
public class ExceptionDialog extends javax.swing.JDialog {

    /** Creates new form OkDialog */
    public ExceptionDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public void setUserError(String error) {
        userError.setText(error);
    }

    public void setException(Throwable e) {
        String stacktrace = "";
        for(StackTraceElement element : e.getStackTrace()) {
            stacktrace += "\n" + element.toString();
        }
        exception.setText(stacktrace);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        userErrorPane = new javax.swing.JScrollPane();
        userError = new javax.swing.JTextArea();
        exceptionPane = new javax.swing.JScrollPane();
        exception = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setTitle("Fehler");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 200));

        userError.setColumns(20);
        userError.setEditable(false);
        userError.setRows(5);
        userErrorPane.setViewportView(userError);

        jTabbedPane1.addTab("Fehlermeldung", userErrorPane);

        exception.setColumns(20);
        exception.setEditable(false);
        exception.setRows(5);
        exceptionPane.setViewportView(exception);

        jTabbedPane1.addTab("Debug Ausgabe", exceptionPane);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose();
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose();
    }//GEN-LAST:event_closeDialog

    private void doClose() {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea exception;
    private javax.swing.JScrollPane exceptionPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea userError;
    private javax.swing.JScrollPane userErrorPane;
    // End of variables declaration//GEN-END:variables

}
