/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModelView.java
 *
 * Created on 19.03.2009, 08:50:08
 */

package bz.asd.autodb.gui;

import bz.asd.mvc.Controller;
import bz.asd.autodb.data.DefaultModel;
import bz.asd.autodb.data.Model;
import bz.asd.autodb.logic.ModelViewController;
import bz.asd.mvc.View;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author lars
 */
public class ModelView extends javax.swing.JPanel implements View {

    private ModelViewController controller;

    /** Creates new empty ModelView which can be used independently
     * for Model GUI IO.
     */
    public ModelView() {
        initComponents();
    }

    public void setModel(bz.asd.mvc.Model model) {
        System.out.println("TADA!!!");
        
        this.model = (DefaultModel) model;

        for(Binding binding : bindingGroup.getBindings()) {
            binding.unbind();
            binding.setSourceObject(model);
            binding.bind();
        }
    }

    public Model getModel() {
        return model;
    }

    public void setController(Controller controller) {
        this.controller = (ModelViewController)controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        model = new bz.asd.autodb.data.DefaultModel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("Hersteller");

        jTextField1.setMinimumSize(new java.awt.Dimension(60, 21));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, model, org.jdesktop.beansbinding.ELProperty.create("${hersteller}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private bz.asd.autodb.data.DefaultModel model;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
