/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModelView.java
 *
 * Created on 19.03.2009, 08:50:08
 */

package bz.asd.autodb.gui;

import bz.asd.mvc.Controller;
import bz.asd.autodb.data.Model;
import bz.asd.autodb.logic.ModelViewController;
import bz.asd.mvc.View;

/**
 *
 * @author lars
 */
public class ModelView extends javax.swing.JPanel implements View {

    private Model model;
    private ModelViewController controller;

    /** Creates new form ModelView */
    public ModelView() {
        
    }

    public void setModel(bz.asd.mvc.Model model) {
        System.out.println("TADA!!!");
        this.model = (Model) model;
        if(model != null) initComponents();
        //TODO Beans Binding
    }

    public void setController(Controller controller) {
        this.controller = (ModelViewController)controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
