package bz.asd.autodb.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScrollControl.java
 *
 * Created on 26.01.2009, 07:46:38
 */

/**
 *
 * @author lars
 */
public class ScrollControl extends javax.swing.JPanel {

    /** Creates new form ScrollControl */
    public ScrollControl() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        prevButton.setText("<<");
        add(prevButton);

        nextButton.setText(">>");
        add(nextButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    // End of variables declaration//GEN-END:variables

}
