/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreeView.java
 *
 * Created on 26.01.2009, 19:21:01
 */

package bz.asd.autodb.gui;

/**
 *
 * @author lars
 */
public class TreeView extends javax.swing.JPanel {

    /** Creates new form TreeView */
    public TreeView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollControl1 = new bz.asd.autodb.gui.ScrollControl();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        searchField = new javax.swing.JTextField();

        setPreferredSize(null);
        setLayout(new java.awt.BorderLayout());
        add(scrollControl1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
        add(searchField, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private bz.asd.autodb.gui.ScrollControl scrollControl1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

}
