/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreeView.java
 *
 * Created on 26.01.2009, 19:21:01
 */

package bz.asd.autodb.gui;

import bz.asd.autodb.data.GroupTree;
import bz.asd.autodb.logic.TreeViewController;
import bz.asd.mvc.Controller;
import bz.asd.mvc.Model;
import bz.asd.mvc.View;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author lars
 */
public class TreeView extends javax.swing.JPanel implements View {

    private TreeViewController controller;

    /** Creates new form TreeView */
    public TreeView(Controller controller) {
        setController(controller);
        initComponents();
    }

    public void setModel(Model model) {
        jTree1.setModel((GroupTree) model);
    }

    public void setController(Controller controller) {
        this.controller = (TreeViewController)controller;
        //always null...
        //if(jTree1 != null) ((GroupTreeView)jTree1).setController(this.controller);
    }

    public TreeNode getSelectedNode() {
        TreePath path = jTree1.getSelectionPath();
        TreeNode node = null;
        if(path != null) node = (TreeNode) path.getLastPathComponent();
        return node;
    }

    public void selectNode(DefaultMutableTreeNode node) {
        TreePath path = new TreePath(node.getPath());
        jTree1.setSelectionPath(path);
		jTree1.scrollPathToVisible(path);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollControl1 = new bz.asd.autodb.gui.ScrollControl();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new GroupTreeView(controller);
        searchField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        scrollControl1.setController(controller);
        add(scrollControl1, java.awt.BorderLayout.NORTH);

        jTree1.setRootVisible(false);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
        add(searchField, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
        // change jTree expansion event from double click to single click
        TreePath oldPath = jTree1.getPathForLocation(evt.getX(), evt.getY());
        if(oldPath == null) return; // no path selected

        DefaultMutableTreeNode node = (DefaultMutableTreeNode)oldPath.getLastPathComponent();
        if(!node.isLeaf()) {
            TreePath newPath = oldPath.pathByAddingChild(node.getChildAt(0));

            // toggle open close path
            if(jTree1.isExpanded(oldPath)) {
                jTree1.collapsePath(oldPath);
            } else {
                jTree1.scrollPathToVisible(newPath);
            }
        }
    }//GEN-LAST:event_jTree1MousePressed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        if(!evt.isAddedPath()) return; // do not handel events from deleted nodes
        
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)evt.getPath().getLastPathComponent();
        if(node.isLeaf()) {
            System.out.println("display "+node);
            controller.treeSelectLeaf(node);
        } else {
            System.out.println("display group: "+node);
            controller.treeSelectInnerNode(node);
        }
    }//GEN-LAST:event_jTree1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private bz.asd.autodb.gui.ScrollControl scrollControl1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables



}
